name: http_apis_generate
description: Client-side development dependency to generate HTTP APIs boilerplate based on http_apis_define
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  http_apis_define:
    path: ../define
  http: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
